version: "3.7"

services:
  webapp:
    build:
      context: .
    restart: always
    container_name: api-boilerplate
    env_file: .env.local
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - .:/home/app
      - ./node_modules:/home/app/node_modules
    ports:
      - 3333:3333
    networks:
      - api-boilerplate
  mongo:
    image: "mongo"
    container_name: boilerplate-mongo
    environment:
      MONGO_INITDB_DATABASE: boilerplate
    ports:
      - "27017:27017"
    volumes:
      - ./mongoData:/data/db
    networks:
      - api-boilerplate
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - api-boilerplate
    depends_on:
      - mongo
networks:
  api-boilerplate:
    driver: bridge
